package test_service_health 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type TestServiceHealthJob struct {

	/*Cc - Descr: Username to authenticate with Default: <nil>
*/
	Cc *Cc `yaml:"cc,omitempty"`

	/*Gemfire - Descr: Name of service registered with cloud controller Default: <nil>
*/
	Gemfire *Gemfire `yaml:"gemfire,omitempty"`

	/*Broker - Descr: Gemfire service broker API address Default: <nil>
*/
	Broker *Broker `yaml:"broker,omitempty"`

}