package test_cluster_health 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type TestClusterHealthJob struct {

	/*Gemfire - Descr: Port the Locator is listening on Default: 55221
*/
	Gemfire *Gemfire `yaml:"gemfire,omitempty"`

}