package locator 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Gemfire struct {

	/*Locator - Descr: Port the Locator will listen on for REST API Default: 8080
*/
	Locator *Locator `yaml:"locator,omitempty"`

	/*Authn - Descr: do we want to enable authentication for this deployment Default: false
*/
	Authn *Authn `yaml:"authn,omitempty"`

	/*ClusterTopology - Descr: Current topology Default: 2
*/
	ClusterTopology *ClusterTopology `yaml:"cluster_topology,omitempty"`

}